# Site settings

title: Neo # Title of your site
email: zheshineo@gmail.com 

description: > 
  Neo's  Blog concerning Tech & Life
baseurl: "" 
url: "http://www.im-neo.com" 

github_username:     RockNeo  
facebook_username:    Neo Socket  


# Build settings
markdown: kramdown
